export type { CommentData, SelectItems } from './model/types/post.types'
export { Comment } from './ui/Comment/Comment'
export { HeaderPostComments } from './ui/HeaderPostComments/HeaderPostComments'
export { PostComments } from './ui/PostComments/PostComments'
export { PostInfo } from './ui/PostInfo/PostInfo'
export { UserBanner } from './ui/UserBanner/UserBanner'
